export const MESSAGE = {
  SYSTEM: {
    ENV_FILE_NOT_FOUND: 'Khong tim thay file .env',
    INVALID_ENV: 'Cac gia tri khong hop le',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    RECORD_ALREADY_EXISTS: 'Record already exists',
    RECORD_NOT_FOUND: 'Record not found',
  },
  AUTH: {
    NOT_LOGGED_IN: 'Chua dang nhap',
    USER_NOT_FOUND: 'User not found',
    ACCOUNT_INACTIVE: 'Account is inactive',
    ACCOUNT_BLOCKED: 'Account is blocked',
    ACCOUNT_ALREADY_EXISTS_UNVERIFIED: 'Account already exists but is not verified',
    EMAIL_ALREADY_REGISTERED: 'Email is already registered',
    PHONE_ALREADY_REGISTERED: 'Phone number is already registered',
    EMAIL_OR_PASSWORD_INCORRECT: 'Email or password is incorrect',
    REFRESH_TOKEN_INVALID: 'Refresh token is invalid',
    DEVICE_INACTIVE: 'Device is inactive',
    LOGOUT_SUCCESSFUL: 'Logout successful',
    EMAIL_ALREADY_VERIFIED: 'Email is already verified',
    VERIFICATION_CODE_INVALID: 'Verification code is invalid',
    VERIFICATION_CODE_EXPIRED: 'Verification code has expired',
    EMAIL_VERIFIED_SUCCESSFULLY: 'Email verified successfully',
    USER_ALREADY_ACTIVE: 'User is already active',
    RESEND_CODE_RATE_LIMIT: 'You can only request a new code once per minute',
    VERIFICATION_CODE_RESENT_SUCCESSFULLY: 'Verification code resent successfully',
    RESET_CODE_INVALID_OR_EXPIRED: 'Reset code is invalid or expired',
    PASSWORD_RESET_SUCCESSFULLY: 'Password reset successfully',
    RESET_CODE_SENT: 'If the email exists, a reset code has been sent',
    TWO_FACTOR_AUTHENTICATION_NOT_ENABLED: 'Two-factor authentication is not enabled for this account',
    INVALID_TWO_FACTOR_AUTHENTICATION_CODE: 'Invalid two-factor authentication code',
    TWO_FACTOR_AUTHENTICATION_ALREADY_DISABLED: 'Two-factor authentication is already disabled',
    TWO_FACTOR_AUTHENTICATION_DISABLED: 'Two-factor authentication has been disabled',
    PASSWORD_INCORRECT: 'Password is incorrect',
    TWO_FACTOR_CHALLENGE_INVALID_OR_EXPIRED: 'Two-factor authentication challenge is invalid or expired',
    RECOVERY_CODE_INVALID: 'Invalid recovery code',
  },
  VALIDATION: {
    PASSWORD_CONFIRMATION_MISMATCH: 'Password and confirm password must match',
    REFRESH_TOKEN_REQUIRED: 'Refresh token is required',
    PHONE_NUMBER_LENGTH: 'Phone number must be 10 digits',
    VERIFICATION_CODE_LENGTH: 'Verification code must be 6 digits',
    RESET_CODE_LENGTH: 'Reset code must be 6 digits',
    VALIDATION_FAILED: 'Validation failed',
  },
  EMAIL: {
    VERIFICATION_CODE_SUBJECT: 'Email Verification Code',
    VERIFICATION_CODE_TEXT: (code: string) => `Your verification code is: ${code}`,
  },
} as const
