export const MESSAGE = {
  SYSTEM: {
    ENV_FILE_NOT_FOUND: 'Khong tim thay file .env',
    INVALID_ENV: 'Cac gia tri khong hop le',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    RECORD_ALREADY_EXISTS: 'Record already exists',
    RECORD_NOT_FOUND: 'Record not found',
  },
  AUTH: {
    NOT_LOGGED_IN: 'Chua dang nhap',
    USER_NOT_FOUND: 'User not found',
    ACCOUNT_INACTIVE: 'Account is inactive',
    ACCOUNT_BLOCKED: 'Account is blocked',
    ACCOUNT_ALREADY_EXISTS_UNVERIFIED: 'Account already exists but is not verified',
    EMAIL_ALREADY_REGISTERED: 'Email is already registered',
    PHONE_ALREADY_REGISTERED: 'Phone number is already registered',
    EMAIL_OR_PASSWORD_INCORRECT: 'Email or password is incorrect',
    REFRESH_TOKEN_INVALID: 'Refresh token is invalid',
    DEVICE_INACTIVE: 'Device is inactive',
    LOGOUT_SUCCESSFUL: 'Logout successful',
    EMAIL_ALREADY_VERIFIED: 'Email is already verified',
    VERIFICATION_CODE_INVALID: 'Verification code is invalid',
    VERIFICATION_CODE_EXPIRED: 'Verification code has expired',
    EMAIL_VERIFIED_SUCCESSFULLY: 'Email verified successfully',
    USER_ALREADY_ACTIVE: 'User is already active',
    RESEND_CODE_RATE_LIMIT: 'You can only request a new code once per minute',
    VERIFICATION_CODE_RESENT_SUCCESSFULLY: 'Verification code resent successfully',
    RESET_CODE_INVALID_OR_EXPIRED: 'Reset code is invalid or expired',
    PASSWORD_RESET_SUCCESSFULLY: 'Password reset successfully',
    RESET_CODE_SENT: 'If the email exists, a reset code has been sent',
    TWO_FACTOR_AUTHENTICATION_NOT_ENABLED: 'Two-factor authentication is not enabled for this account',
    INVALID_TWO_FACTOR_AUTHENTICATION_CODE: 'Invalid two-factor authentication code',
    TWO_FACTOR_AUTHENTICATION_ALREADY_DISABLED: 'Two-factor authentication is already disabled',
    TWO_FACTOR_AUTHENTICATION_DISABLED: 'Two-factor authentication has been disabled',
    PASSWORD_INCORRECT: 'Password is incorrect',
    TWO_FACTOR_CHALLENGE_INVALID_OR_EXPIRED: 'Two-factor authentication challenge is invalid or expired',
    RECOVERY_CODE_INVALID: 'Invalid recovery code',
    TWO_FACTOR_AUTHENTICATION_ALREADY_ENABLED: 'Two-factor authentication is already enabled',
    TWO_FACTOR_AUTHENTICATION_SETUP_REQUIRED: 'Two-factor authentication setup is required',
    TWO_FACTOR_AUTHENTICATION_ENABLED: 'Two-factor authentication has been enabled',
  },
  VALIDATION: {
    PASSWORD_CONFIRMATION_MISMATCH: 'Password and confirm password must match',
    REFRESH_TOKEN_REQUIRED: 'Refresh token is required',
    PHONE_NUMBER_LENGTH: 'Phone number must be 10 digits',
    VERIFICATION_CODE_LENGTH: 'Verification code must be 6 digits',
    RESET_CODE_LENGTH: 'Reset code must be 6 digits',
    VALIDATION_FAILED: 'Validation failed',
    TWO_FACTOR_TOKEN_REQUIRED: 'twoFactorToken is required',
    USER_REQUIRED: 'user is required',
    ACCESS_TOKEN_REQUIRED: 'accessToken is required',
  },
  EMAIL: {
    VERIFICATION_CODE_SUBJECT: 'Email Verification Code',
    VERIFICATION_CODE_TEXT: (code: string) => `Your verification code is: ${code}`,
  },
  PAYMENT: {
    ORDER_NOT_FOUND: 'Order not found',
    ORDER_NOT_AWAITING_PAYMENT: 'Order is not awaiting payment',
    PAYMENT_CANNOT_BE_RETRIED: 'Payment cannot be retried',
    PAYMENT_COULD_NOT_BE_CREATED: 'Payment could not be created for this order',
    PAYMENT_NOT_FOUND: 'Payment not found',
    PAYMENT_AMOUNT_MISMATCH: 'Payment amount mismatch',
    PAYMENT_STATUS_CANNOT_BE_UPDATED: 'Payment status cannot be updated',
    ORDER_STATUS_CANNOT_BE_UPDATED: 'Order status cannot be updated',
    INVALID_PAYOS_WEBHOOK_PAYLOAD: 'Invalid PayOS webhook payload',
    INVALID_WEBHOOK_PAYLOAD: 'Invalid webhook payload',
  },
  BRAND: {
    NOT_FOUND: 'Brand not found',
    CANNOT_DELETE_WITH_ACTIVE_PRODUCTS: 'Cannot delete brand with active products',
    DELETED_SUCCESSFULLY: 'Brand deleted successfully',
  },
  CART: {
    SKU_NOT_FOUND: 'SKU not found',
    SKU_OUT_OF_STOCK: 'SKU is out of stock',
    QUANTITY_EXCEEDS_STOCK: 'Quantity exceeds available stock',
    ITEM_NOT_FOUND: 'Cart item not found',
    ITEM_DELETED_SUCCESSFULLY: 'Cart item deleted successfully',
    CLEARED_SUCCESSFULLY: 'Cart cleared successfully',
  },
  CATEGORY: {
    PARENT_CANNOT_BE_ITSELF: 'Parent category cannot be itself',
    PARENT_NOT_FOUND: 'Parent category not found',
    NOT_FOUND: 'Category not found',
    CANNOT_DELETE_WITH_ACTIVE_CHILDREN: 'Cannot delete category with active child categories',
    DELETED_SUCCESSFULLY: 'Category deleted successfully',
  },
  ORDER: {
    CART_EMPTY: 'Cart is empty',
    ADDRESS_NOT_FOUND: 'Address not found',
    SKU_NO_LONGER_AVAILABLE: (skuId: number) => `SKU ${skuId} is no longer available`,
    INSUFFICIENT_STOCK_FOR_SKU: (skuId: number) => `Insufficient stock for SKU ${skuId}`,
    NOT_FOUND: 'Order not found',
    CANNOT_BE_CANCELLED: 'Order cannot be cancelled',
    INVALID_STATUS_TRANSITION: 'Invalid order status transition',
  },
  PRODUCT: {
    DUPLICATE_VARIANT_NAMES: 'Duplicate variant names',
    DUPLICATE_OPTIONS_IN_VARIANT: (variantName: string) => `Duplicate options in variant "${variantName}"`,
    MIN_PRICE_GREATER_THAN_MAX_PRICE: 'Min price cannot be greater than max price',
    NOT_FOUND: 'Product not found',
    BRAND_NOT_FOUND: 'Brand not found',
    DUPLICATE_CATEGORY_IDS: 'Duplicate category ids',
    CATEGORY_NOT_FOUND: 'Category not found',
    VIRTUAL_PRICE_LESS_THAN_BASE_PRICE: 'Virtual price cannot be less than base price',
    CANNOT_UPDATE_VARIANTS_WITH_ACTIVE_SKUS: 'Cannot update variants when there are active SKUs',
    DELETED_SUCCESSFULLY: 'Product deleted successfully',
  },
  SKU: {
    INVALID_PRODUCT_VARIANTS: 'Invalid product variants',
    VALUE_DOES_NOT_MATCH_PRODUCT_VARIANTS: 'SKU value does not match product variants',
    MISSING_VARIANT: (variantName: string) => `Missing variant "${variantName}"`,
    INVALID_OPTION_FOR_VARIANT: (option: string, variantName: string) =>
      `Invalid option "${option}" for variant "${variantName}"`,
    VARIANT_COMBINATION_ALREADY_EXISTS: 'SKU with this variant combination already exists',
    NOT_FOUND: 'SKU not found',
    DELETED_SUCCESSFULLY: 'SKU deleted successfully',
  },
  USER: {
    PHONE_NUMBER_ALREADY_IN_USE: 'Phone number already in use',
    CURRENT_PASSWORD_INCORRECT: 'Current password is incorrect',
    PASSWORD_CHANGED_SUCCESSFULLY: 'Password changed successfully',
  },
  AUTHORIZATION: {
    USER_CONTEXT_NOT_FOUND: 'User context not found',
    ACCESS_DENIED: 'Access denied',
  },
  STORAGE: {
    UNSUPPORTED_FILE_TYPE: 'Unsupported file type',
  },
  REVIEW: {
    NOT_ELIGIBLE: 'You are not eligible to review this product',
    ALREADY_EXISTS: 'This product has already been reviewed for this order',
    NOT_FOUND: 'Review not found',
    UPDATE_LIMIT_REACHED: 'Review update limit has been reached',
    DELETED_SUCCESSFULLY: 'Review deleted successfully',
    MEDIA_LIMIT_REACHED: 'A review can contain at most 5 media files',
    MEDIA_NOT_FOUND: 'Review media not found',
    MEDIA_DELETED_SUCCESSFULLY: 'Review media deleted successfully',
  },
  ADDRESS: {
    NOT_FOUND: 'Address not found',
    DELETED_SUCCESSFULLY: 'Address deleted successfully',
  },
} as const
